const InsuranceCompanies = [
    "Acko General Insurance Company",
    "Aditya Birla General Insurance Company",
    "Bajaj Allianz General Insurance Company",
    "Care Health Insurance",
    "Cholamandalam MS General Insurance",
    "Digit Insurance",
    "East West Assist Insurance TPA Private Limited",
    "Ericson Insurance TPA Pvt. Ltd.",
    "Family Health Plan TPA Limited",
    "Future Generali General Insurance",
    "Good Health Insurance TPA Ltd",
    "HDFC ERGO General Insurance Company",
    "Health Insurance TPA of India Ltd",
    "HealthIndia Insurance TPA Services Pvt. Ltd.",
    "Heritage Health Insurance TPA Pvt Ltd",
    "ICICI Lombard General Insurance Company Limited",
    "IFFCO Tokio General Insurance Company Limited",
    "Liberty General insurance Limited",
    "ManipalCigna Health Insurance Company Ltd",
    "MDIndia Health Insurance TPA Private Limited",
    "MD India - Govt",
    "MD India - Pensioner",
    "Medi Assist Insurance TPA Private Limited",
    "Medi Assist - Govt",
    "Medi Assist - Pensioner",
    "Med Save Insurance TPA Pvt., Ltd.,",
    "Medvantage Insurance TPA",
    "Navi General Insurance",
    "TNNHIS",
    "Niva Bupa General Insurance",
    "Paramount Health Services And Insurance TPA",
    "Pradhan Mantri Jan Arogya Yojana (PM-JAY)",
    "Raksha Health Insurance TPA Pvt Ltd",
    "Reliance General Insurance",
    "SafeWay Insurance TPA Pvt., Ltd.,",
    "SBI General Insurance",
    "Star Health and Allied Insurance",
    "Tata AIG General Insurance Company Limited",
    "Universal Sompo General Insurance Company Ltd",
    "Vidal Health Insurance TPA"
  ];
  
  export default InsuranceCompanies;
  